# Build solite wheels.
#
# Assumed to run as a subworkflow of .github/workflows/release.yml; specifically, as a local
# artifacts job within `cargo-dist`.
# 
# courtesy: https://github.com/astral-sh/uv/blob/34b5afcba6c89046cf8eb97efb15ae3d18015570/.github/workflows/build-binaries.yml#L57
name: "Build PyPi wheels"

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  macos-x86_64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@v6
      - run: uvx maturin build -b bin --release --locked --out dist/ --target x86_64-apple-darwin
        working-directory: crates/solite-cli
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: wheels_solite-macos-x86_64
          path: crates/solite-cli/dist
  macos-aarch64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@v6
      - run: uvx maturin build -b bin --release --locked --out dist/
        working-directory: crates/solite-cli
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: wheels_solite-macos-aarch64
          path: crates/solite-cli/dist
  linux-x86_64:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@v6
      - run: uvx maturin build -b bin --release --locked --out dist/
        working-directory: crates/solite-cli
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: wheels_solite-linux-x86_64
          path: crates/solite-cli/dist