# Build uv on all platforms.
#
# Generates wheels for PyPi
#
# Assumed to run as a subworkflow of .github/workflows/release.yml; specifically, as a local
# artifacts job within `cargo-dist`.
# courtesy: https://github.com/astral-sh/uv/blob/34b5afcba6c89046cf8eb97efb15ae3d18015570/.github/workflows/build-binaries.yml#L57
name: "Build PyPi wheels"

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  macos-x86_64:
    runs-on: macos-14
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@v6
      - run: uvx maturin build -b bin --release --locked --out dist/
        working-directory: crates/solite-cli
      - run: uv publish dist/*
        working-directory: crates/solite-cli