name: "build"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
        shell: bash
      - run: |
          echo $PATH; 
          uv tool install --with ipykernel jupyter-core
          cargo run -- jupyter --install
        shell: bash
      - run: make test
        shell: bash
      - run: ls -lah target/debug
      #- run: make all; ./dist/debug/sqlite3 < smoke.sql
      #  working-directory: solite-stdlib/sqlite3
